remote_theme: poole/lanyon

# Setup
title:               Edtec
tagline:             'Learning to earn alongside AI'
description:         'A learning blog. And hopefully one day an earning blog. Made by <a href="https://twitter.com/adamedtec" target="_blank">@adamedtec</a>.'
url:                 http://edtec.ai
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Adam Rudd
  url:               https://twitter.com/adamedtec
  email:             adam@edtec.ai

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-62Q05YSKJF
